### ISSUE TITLE
reinstall 

### ISSUE THREAD

**Issue by rhgiter** [custom-cards/spotify-card#137] opened 2021-02-07 08:06 UTC
how do i remove or reinstall this ?   i cant find it in HACS, but when i will reinstall it , i get this Repository 'custom-cards/spotify-card' exists in the store.

its not in the folder 'custom_components'

?

**Comment by FL550** [comment] 2021-02-07 12:31
You can find it in the folder www/community

**Comment by rhgiter** [comment] 2021-02-08 16:15
no , its not there.... :-/

![image](https://user-images.githubusercontent.com/61065752/107247140-43e5af80-6a31-11eb-92e6-7ae7c9b0795d.png)

**Comment by FL550** [comment] 2021-02-10 12:21
Can you then give more details on the error you encounter?

**Comment by rhgiter** [comment] 2021-02-10 13:32
i get this error when i will play a playlist on my google home mini speaker
![image](https://user-images.githubusercontent.com/61065752/107516503-ccd52600-6bac-11eb-9e47-59442b07f780.png)

![image](https://user-images.githubusercontent.com/61065752/107516551-dced0580-6bac-11eb-8c04-f6d5d0f38877.png)

**Comment by rhgiter** [comment] 2021-02-10 13:33
spotcast plugin  works and spotify plug in also work

**Comment by FL550** [comment] 2021-02-10 13:35
Ok, but this is another error. Can you please specify the error you get when you try to reinstall?

**Comment by rhgiter** [comment] 2021-02-10 14:39
![image](https://user-images.githubusercontent.com/61065752/107524578-386fc100-6bb6-11eb-800b-490d7df7296c.png)

**Comment by FL550** [comment] 2021-02-10 14:44
Ok, the problem is exactly what's stated in the error message. You don't have to add the GitHub URL manually, it's already available in the store. Just search for it.

**Comment by rhgiter** [comment] 2021-02-10 15:02
Thanks , I think my HACS installation was not working proberly, i've reinstalled it, and now i can search for it.

**Comment by FL550** [comment] 2021-02-10 15:07
Ok, i'll close this for now.

**Closed by FL550** 2021-02-10 15:07 UTC
