### ISSUE TITLE
Player command failed: Restriction violated

### ISSUE THREAD

**Issue by fredamn76** [custom-cards/spotify-card#31] opened 2019-10-19 15:25 UTC
Its currently not possible to choose player on my Spotify-card then music isnt playing on any device. I'm on version 1.9 of Spotify-Card and HA version is 0.100.2.
```
Log Details (ERROR)
Sat Oct 19 2019 17:20:15 GMT+0200 (centraleuropeisk sommartid)
http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd:
 Player command failed: Restriction violated
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 121, in _internal_call
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 206, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat)
  File "/config/custom_components/spotcast/__init__.py", line 116, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 948, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd:
 Player command failed: Restriction violated
```

**Comment by fondberg** [comment] 2019-10-20 17:00
what is your configuration? have you enabled transfer_playback by any chance?

**Comment by fondberg** [comment] 2019-10-20 17:01
and does it work to play using a service call to spotcast?

**Comment by fredamn76** [comment] 2019-10-21 04:30
My current configuration:

client_id: myclientid
limit: 25
random_song: true
transfer_playback: true
type: 'custom:spotify-card'

**Comment by fondberg** [comment] 2019-10-21 07:14
random_song is not yet implemented in the spotify card.
also can you remove transfer_playback and try again?

**Comment by fredamn76** [comment] 2019-10-21 08:59
i removed random_song but it still does not work. If i use service call starting track works.

**Comment by fondberg** [comment] 2019-10-21 16:55
It almost looks like an issue that is known but then starting a playback using spotcast directly wouldn't work.
The error you posted is from spotcast. I'm taking it that you tested on 2 chromecast devices. Can you add debug to spotcast 
```
logger:
  default: info
  logs:
    custom_components.spotcast: debug
```
And do one which works using the service call and one from the card which doesn't work?

**Comment by fredamn76** [comment] 2019-10-22 20:06
```

2019-10-22 22:01:11 INFO (SyncWorker_8) [pychromecast] Querying device status
2019-10-22 22:01:11 DEBUG (SyncWorker_8) [custom_components.spotcast.sensor] Found chromecast devices: [Chromecast('192.168.1.223', port=8009, device=DeviceStatus(friendly_name='Stora sovrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('2313e510-36f2-359f-0177-1fa6917a8300'), cast_type='audio')), Chromecast('192.168.1.49', port=8009, device=DeviceStatus(friendly_name='Vardagsrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('1ac2c8f6-eef0-e98b-f15a-d24ccc09cea5'), cast_type='audio')), Chromecast('192.168.1.223', port=42164, device=DeviceStatus(friendly_name='Övervåningen', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('36a0aa1e-f810-4088-819f-33bb881673f1'), cast_type='group')), Chromecast('192.168.1.223', port=46368, device=DeviceStatus(friendly_name='Alla', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('5ca61429-1dd4-4498-8a9f-fe0fc6b94e81'), cast_type='group')), Chromecast('192.168.1.92', port=8009, device=DeviceStatus(friendly_name='Philip Chromecast', model_name='Chromecast', manufacturer='Unknown manufacturer', uuid=UUID('7d0b27b2-07b7-d827-b14c-6e3eb9025485'), cast_type='cast')), Chromecast('192.168.1.117', port=8009, device=DeviceStatus(friendly_name='Köket högtalare', model_name='Google Home', manufacturer='Unknown manufacturer', uuid=UUID('ca55a241-5ea9-2c33-1d4b-589c2712ad35'), cast_type='audio')), Chromecast('192.168.1.117', port=42299, device=DeviceStatus(friendly_name='Nere', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('b14d36a1-fa6f-4ac9-b3cf-e1365e28d38b'), cast_type='group')), Chromecast('192.168.1.72', port=8009, device=DeviceStatus(friendly_name='Philips speaker', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('e458c89d-1c43-9e59-35e8-87da44d6a11e'), cast_type='audio')), Chromecast('192.168.1.206', port=8009, device=DeviceStatus(friendly_name='SHIELD', model_name='SHIELD Android TV', manufacturer='NVIDIA', uuid=UUID('b5b2bf22-99e7-f696-3841-23f8057dd3e0'), cast_type='cast'))]
2019-10-22 22:01:16 DEBUG (SyncWorker_5) [custom_components.spotcast] cast info: ChromecastInfo(host='192.168.1.223', port=8009, service='Chromecast-Audio-2313e51036f2359f01771fa6917a8300._googlecast._tcp.local.', uuid='2313e510-36f2-359f-0177-1fa6917a8300', manufacturer='Unknown manufacturer', model_name='Chromecast Audio', friendly_name='Stora sovrummet', is_dynamic_group=None)
2019-10-22 22:01:16 INFO (SyncWorker_5) [pychromecast] Querying device status
2019-10-22 22:01:16 DEBUG (SyncWorker_5) [custom_components.spotcast] Found cast device: Chromecast('192.168.1.223', port=8009, device=DeviceStatus(friendly_name='Stora sovrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid='2313e510-36f2-359f-0177-1fa6917a8300', cast_type='audio'))
2019-10-22 22:01:16 INFO (Thread-245) [pychromecast.controllers] Receiver:Launching app CC32E753
2019-10-22 22:01:18 DEBUG (SyncWorker_5) [custom_components.spotcast] Version: 2.4.0, playing URI: spotify:playlist:1XgGoGkuNcRdKJf7br1kPr on device-id: 2f75e60ce0f248e0b9df03415ad95ebd
2019-10-22 22:01:18 DEBUG (SyncWorker_5) [custom_components.spotcast] Start playback at random position: 15
2019-10-22 22:01:18 DEBUG (SyncWorker_5) [custom_components.spotcast] Playing context uri using context_uri for uri: "spotify:playlist:1XgGoGkuNcRdKJf7br1kPr" (random_song: True)

2019-10-22 22:01:41 INFO (SyncWorker_9) [pychromecast] Quiting current app
2019-10-22 22:01:41 INFO (SyncWorker_9) [pychromecast.controllers] Receiver:Stopping current app 'CC32E753'

2019-10-22 22:01:42 DEBUG (SyncWorker_5) [custom_components.spotcast.sensor] Found chromecast devices: [Chromecast('192.168.1.223', port=8009, device=DeviceStatus(friendly_name='Stora sovrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('2313e510-36f2-359f-0177-1fa6917a8300'), cast_type='audio')), Chromecast('192.168.1.49', port=8009, device=DeviceStatus(friendly_name='Vardagsrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('1ac2c8f6-eef0-e98b-f15a-d24ccc09cea5'), cast_type='audio')), Chromecast('192.168.1.223', port=42164, device=DeviceStatus(friendly_name='Övervåningen', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('36a0aa1e-f810-4088-819f-33bb881673f1'), cast_type='group')), Chromecast('192.168.1.223', port=46368, device=DeviceStatus(friendly_name='Alla', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('5ca61429-1dd4-4498-8a9f-fe0fc6b94e81'), cast_type='group')), Chromecast('192.168.1.92', port=8009, device=DeviceStatus(friendly_name='Philip Chromecast', model_name='Chromecast', manufacturer='Unknown manufacturer', uuid=UUID('7d0b27b2-07b7-d827-b14c-6e3eb9025485'), cast_type='cast')), Chromecast('192.168.1.72', port=8009, device=DeviceStatus(friendly_name='Philips speaker', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('e458c89d-1c43-9e59-35e8-87da44d6a11e'), cast_type='audio')), Chromecast('192.168.1.117', port=8009, device=DeviceStatus(friendly_name='Köket högtalare', model_name='Google Home', manufacturer='Unknown manufacturer', uuid=UUID('ca55a241-5ea9-2c33-1d4b-589c2712ad35'), cast_type='audio')), Chromecast('192.168.1.117', port=42299, device=DeviceStatus(friendly_name='Nere', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('b14d36a1-fa6f-4ac9-b3cf-e1365e28d38b'), cast_type='group')), Chromecast('192.168.1.206', port=8009, device=DeviceStatus(friendly_name='SHIELD', model_name='SHIELD Android TV', manufacturer='NVIDIA', uuid=UUID('b5b2bf22-99e7-f696-3841-23f8057dd3e0'), cast_type='cast'))]

2019-10-22 22:02:13 INFO (SyncWorker_4) [pychromecast] Querying device status
2019-10-22 22:02:13 DEBUG (SyncWorker_4) [custom_components.spotcast.sensor] Found chromecast devices: [Chromecast('192.168.1.206', port=8009, device=DeviceStatus(friendly_name='SHIELD', model_name='SHIELD Android TV', manufacturer='NVIDIA', uuid=UUID('b5b2bf22-99e7-f696-3841-23f8057dd3e0'), cast_type='cast')), Chromecast('192.168.1.223', port=8009, device=DeviceStatus(friendly_name='Stora sovrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('2313e510-36f2-359f-0177-1fa6917a8300'), cast_type='audio')), Chromecast('192.168.1.223', port=42164, device=DeviceStatus(friendly_name='Övervåningen', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('36a0aa1e-f810-4088-819f-33bb881673f1'), cast_type='group')), Chromecast('192.168.1.223', port=46368, device=DeviceStatus(friendly_name='Alla', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('5ca61429-1dd4-4498-8a9f-fe0fc6b94e81'), cast_type='group')), Chromecast('192.168.1.92', port=8009, device=DeviceStatus(friendly_name='Philip Chromecast', model_name='Chromecast', manufacturer='Unknown manufacturer', uuid=UUID('7d0b27b2-07b7-d827-b14c-6e3eb9025485'), cast_type='cast')), Chromecast('192.168.1.72', port=8009, device=DeviceStatus(friendly_name='Philips speaker', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('e458c89d-1c43-9e59-35e8-87da44d6a11e'), cast_type='audio')), Chromecast('192.168.1.49', port=8009, device=DeviceStatus(friendly_name='Vardagsrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid=UUID('1ac2c8f6-eef0-e98b-f15a-d24ccc09cea5'), cast_type='audio')), Chromecast('192.168.1.117', port=8009, device=DeviceStatus(friendly_name='Köket högtalare', model_name='Google Home', manufacturer='Unknown manufacturer', uuid=UUID('ca55a241-5ea9-2c33-1d4b-589c2712ad35'), cast_type='audio')), Chromecast('192.168.1.117', port=42299, device=DeviceStatus(friendly_name='Nere', model_name='Google Cast Group', manufacturer='Unknown manufacturer', uuid=UUID('b14d36a1-fa6f-4ac9-b3cf-e1365e28d38b'), cast_type='group'))]

2019-10-22 22:02:18 DEBUG (SyncWorker_9) [custom_components.spotcast] cast info: ChromecastInfo(host='192.168.1.223', port=8009, service='Chromecast-Audio-2313e51036f2359f01771fa6917a8300._googlecast._tcp.local.', uuid='2313e510-36f2-359f-0177-1fa6917a8300', manufacturer='Unknown manufacturer', model_name='Chromecast Audio', friendly_name='Stora sovrummet', is_dynamic_group=None)
2019-10-22 22:02:18 INFO (SyncWorker_9) [pychromecast] Querying device status
2019-10-22 22:02:18 DEBUG (SyncWorker_9) [custom_components.spotcast] Found cast device: Chromecast('192.168.1.223', port=8009, device=DeviceStatus(friendly_name='Stora sovrummet', model_name='Chromecast Audio', manufacturer='Unknown manufacturer', uuid='2313e510-36f2-359f-0177-1fa6917a8300', cast_type='audio'))
2019-10-22 22:02:18 INFO (Thread-264) [pychromecast.controllers] Receiver:Launching app CC32E753
2019-10-22 22:02:21 DEBUG (SyncWorker_9) [custom_components.spotcast] Version: 2.4.0, playing URI: spotify:playlist:6v3KuXI3fgyPprimbRXFjh on device-id: 2f75e60ce0f248e0b9df03415ad95ebd
2019-10-22 22:02:21 DEBUG (SyncWorker_9) [custom_components.spotcast] Playing context uri using context_uri for uri: "spotify:playlist:6v3KuXI3fgyPprimbRXFjh" (random_song: False)
2019-10-22 22:02:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139720482201360] http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd:
 Player command failed: Restriction violated
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 121, in _internal_call
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 206, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat)
  File "/config/custom_components/spotcast/__init__.py", line 116, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 948, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=2f75e60ce0f248e0b9df03415ad95ebd:
 Player command failed: Restriction violated
2019-10-22 22:02:36 INFO (SyncWorker_3) [homeassistant.components.spotify.media_player] New Devices: {'Stora sovrummet': '2f75e60ce0f248e0b9df03415ad95ebd'}
```

**Comment by fondberg** [comment] 2019-10-23 16:04
Very weird... I need to check this more thoroughly when I get some more time.

**Comment by fredamn76** [comment] 2019-10-23 16:11
It worked without problems before upgrading to latest HA 0.100.

**Comment by fondberg** [comment] 2019-11-30 11:10
Is it still failing? I can't reproduce it at all...

**Comment by fredamn76** [comment] 2019-11-30 17:12
I will try and get back to you

**Comment by fredamn76** [comment] 2019-12-11 18:36
Yes, it's still failing.

**Comment by fredamn76** [comment] 2019-12-11 18:48
I found the cause of my issue. According https://github.com/custom-cards/spotify-card/issues/32 i cannot have multiple cards for different users. I removed my childrens cards and then it worked.

**Comment by tasmith8** [comment] 2019-12-11 18:48
I just had this bug happen to me. I am able to reproduce it pretty consistently. The problem occurs when you issue a "/me/player/play" command to a player that is not allowed to play. The not allowed to play is the bug part. I think a player can get orphaned sometimes and before you can play again you need to reactivate the player with a PUT to "/me/player".  if you look at the request, see below, of the GET "/me/player" it shows an active device but is disallowing "resuming". 

I hope that helps you...

{
  "device": {
    "id": "...",
    "is_active": true,
    "is_private_session": false,
    "is_restricted": false,
    "name": "iPhone",
    "type": "Smartphone",
    "volume_percent": 100
  },
  "shuffle_state": false,
  "repeat_state": "off",
  "timestamp": -747,
  "context": null,
  "progress_ms": 0,
  "item": null,
  "currently_playing_type": "unknown",
  **"actions": {
    "disallows": {
      "pausing": true,
      "resuming": true,
      "seeking": true,
      "skipping_prev": true,
      "skipping_next": true
    }
  },**
  "is_playing": false
}

**Comment by fondberg** [comment] 2019-12-11 19:03
Hmmm. That seems like a bug in spotify web api. Can you point me to the docs for that behaviour?

**Comment by tasmith8** [comment] 2019-12-11 19:20
Here are the docs for the call you were making: https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/. 

Here are the docs for transferring playback: https://developer.spotify.com/documentation/web-api/reference/player/transfer-a-users-playback/

I think it should work how you are expecting it too except when the call to GET "/me/player" (https://developer.spotify.com/documentation/web-api/reference/player/get-information-about-the-users-current-playback/) returns a player that is in a state.  that disallows actions.

making the transferring playback call to the same player seems to work fine for me...

**Comment by fredamn76** [comment] 2019-12-11 21:25
Somehow you system show this issue again.

**Comment by fondberg** [comment] 2019-12-17 13:39
@fredamn76 and @tasmith8 is this happening only on chromecast playbacks or also on spotify connect devices (former uses spotcast, latter uses spotify-web-api)?

The logs suggests that it is spotcast which fails and then I guess the fix would be to check if the currentPlayer.actions. disallows. resuming is true or false. Correct?

**Comment by fredamn76** [comment] 2019-12-21 07:58
It's working again. I have no idea what is causing this issue

**Comment by fondberg** [comment] 2020-01-05 13:58
Lets keep this open so that you can add debug info when it happens again

**Comment by fondberg** [comment] 2020-03-28 14:36
now activity in this issue for long. closing

**Closed by fondberg** 2020-03-28 14:36 UTC
Labels: question
