### ISSUE TITLE
List of playlists empty, "spotify integration has to be installed"

### ISSUE THREAD

**Issue by TekniskSupport** [custom-cards/spotify-card#91] opened 2020-07-21 07:48 UTC
Hi,

I updated using HACS to the 2.0beta-x, and now i'm getting
![image](https://user-images.githubusercontent.com/13868526/88024015-526e8700-cb32-11ea-8351-6b3fc55a8fec.png)

This despite i already have spotify integration and spotcast installed.
Solved it temporarily by installing from master.

**Comment by Harry-1976** [comment] 2020-07-21 12:06
I’m having the same issue.

**Comment by fondberg** [comment] 2020-07-21 13:01
What version of hass are you using? Have you tried restarting hass?

**Comment by Harry-1976** [comment] 2020-07-21 13:46
I’m on HA 0.112.4.
Yes, i have restarted hass few times.
I have also installed and configured Spotcast.

**Comment by TekniskSupport** [comment] 2020-07-21 13:58
@fondberg 

Running latest available, usually installing updates soon after they become available.


Home Assistant 0.112.4

Frontend version: 20200702.1 - latest
System Health
arch	x86_64
chassis	desktop
dev	false
docker	true
docker_version	18.06.3-ce
hassio	true
host_os	Ubuntu 17.10
installation_type	Home Assistant Supervised
os_name	Linux
os_version	4.13.0-46-generic
python_version	3.7.7
supervisor	229
timezone	Europe/Stockholm
version	0.112.4
virtualenv	false

Tried restarting hass, also tried reinstalling spotify integration without luck.

@Harry-1976 the beta is not merged with master, so it's the older version (when in hacs you choose reinstall you can choose which version, at the bottom you'll find master)

**Comment by TekniskSupport** [comment] 2020-07-21 14:12
This may be linked to the #92 i opened, but reinstalling the spotify integration (which removed and re-added the entity, didn't solve the issue for me.

**Comment by fondberg** [comment] 2020-07-21 16:57
I assume this issue is for the 2.0 beta. 

For that it is important to have the latest spotcast installed too. Make sure both the card and spotcast are the latest versions.

**Comment by TekniskSupport** [comment] 2020-07-21 17:02
@fondberg The spotify integration is included in home assistant, which i am running latest version of.
And I actually got the card fully working if i hacked the source code to set spotify_installed 1 manually.

You list entites and look for an entity called media_player.spotify_*  which is not necessarily true as i mentioned in #92

**Comment by fondberg** [comment] 2020-07-21 17:08
Spotcast is a custom component which is not installed in HA per default. This is required for v2.

Regarding the naming of the spotify media player, I saw your report. I will see if it can be searched for another way. Things will break if you hack it like you did. At least after a while

**Comment by TekniskSupport** [comment] 2020-07-21 17:11
Yes I understand that it won't work with updates etc..
Spotcast is installed latest version as well.

Thanks for your awesome card btw use it all the time!

**Comment by TekniskSupport** [comment] 2020-07-21 17:18
Just a thougt, Would adding the integration as a dependency in manifest.json be an alternative?
/i

**Comment by fondberg** [comment] 2020-07-21 19:27
There is no manifest for cards, is there?

**Comment by Harry-1976** [comment] 2020-07-21 19:52
@fondberg Thanks for the update. I just tested it but i’m still getting the message. In my case the default media player from previous versions was the correct one. Selecting other devices (echo or chromecast) didn’t make a difference.

What i did notice though is that the default playlist type isn’t loading but the featured playlist and the discover weekly playlist both load. I can play these too.

**Comment by TekniskSupport** [comment] 2020-07-21 20:57
Thanks for the fix!

Sometimes it loads just fine (cache disabled + reload resources) about 1 in 30 times. 
When it does not load i get this error in the js-console:
![image](https://user-images.githubusercontent.com/13868526/88103676-9ea4e000-cba1-11ea-8271-624ab60569e8.png)

Upon reboot i also get the same error in the homeassistant.log:
I got an error in the log
2020-07-21 22:27:31 ERROR (MainThread) [frontend.js.latest.202007021] https:/....../hacsfiles/spotify-card/spotify-card.js:433:3511 Uncaught TypeError: Cannot read property 'connection' of undefined

As it sometimes loads fine, it's not the entity id.
Any idéas?

**Comment by Harry-1976** [comment] 2020-07-21 21:04
Yes, i’m getting same error:

http://homeassistant.local:8123/hacsfiles/spotify-card/spotify-card.js:412:3682 Uncaught TypeError: Cannot read property 'connection' of undefined
http://192.168.68.138:8123/hacsfiles/spotify-card/spotify-card.js:412:25677 TypeError: undefined is not an object (evaluating 'this.hass.connection')

**Comment by pergolafabio** [comment] 2020-07-22 06:21
Hi

first time i installed this card, also see that error, while spotify integration is installed
i dont need spotcast; i dont want to play it on cast devices, i have a denon receiver, i play spotify on a device direct

is then spotcast still needed? cause i wont use it

**Comment by fondberg** [comment] 2020-07-22 06:22
Spotcast is

**Comment by fondberg** [comment] 2020-07-22 06:25
> Yes, i’m getting same error:
> 
> http://homeassistant.local:8123/hacsfiles/spotify-card/spotify-card.js:412:3682 Uncaught TypeError: Cannot read property 'connection' of undefined
> http://....../hacsfiles/spotify-card/spotify-card.js:412:25677 TypeError: undefined is not an object (evaluating 'this.hass.connection')

That is a different error than the issue is about.
It seems like lovelace doesnt send the hass property.

**Comment by fondberg** [comment] 2020-07-22 06:26
@TekniskSupport can i close this now with the release made yday?

**Comment by pergolafabio** [comment] 2020-07-22 06:26
ok, spotcast is installed, i didnt do the minimum config yet
but i also see this error ..... ui.nabu.casa/hacsfiles/spotify-card/spotify-card.js:433:3511 Uncaught TypeError: Cannot read property 'connection' of undefined

**Comment by fondberg** [comment] 2020-07-22 06:28
@pergolafabio you need to configure apotcast

**Comment by pergolafabio** [comment] 2020-07-22 06:37
ok , installed and loaded

You are using a custom integration for spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

no errors, looks ok
but still see the same issue : spotify intergration needs to be installed .... 
also same error connection

first time i restarted HA, i saw the playlist list though, i did a refresh, and list was gone

**Comment by pergolafabio** [comment] 2020-07-22 06:39
did a refresh again, saw the list, but also still the error
refresh again, list gone :)

**Comment by pergolafabio** [comment] 2020-07-22 07:03
see screenshot here, sometimes it works, when i do refresh, the playlist+ devices list is gone

https://www.dropbox.com/s/djcfatlaup50d5t/spotify.PNG?dl=0

**Comment by TekniskSupport** [comment] 2020-07-22 07:09
@fondberg The issue persists unfortunately, but it's not constant it works _sometimes_ and when it does the JS error is not thrown.

**Comment by fondberg** [comment] 2020-07-22 07:35
@TekniskSupport  Can you try https://github.com/custom-cards/spotify-card/releases/tag/v2.0.0-beta.18?

**Comment by pergolafabio** [comment] 2020-07-22 07:45
installed .18 , now a red box with this error : 

No client ---- id
type: 'custom:spotify-card'
limit: 20
display_style: Grid

**Comment by fondberg** [comment] 2020-07-22 08:16
@pergolafabio my bad. try beta20 now

**Comment by TekniskSupport** [comment] 2020-07-22 08:23
Hi,

I tried .18 and .19 but they seemed to work like the old 1x with the authentication box, but working nonetheless.
with the .20 release it was some sort of progress. I still sometimes get the js error, and the warning. but now the playlists are loaded

Not the available playback devices thou.

Left is when it's working, reload and it becomes like the right one
![image](https://user-images.githubusercontent.com/13868526/88153125-46072e80-cc05-11ea-86a3-be54a59a35b0.png)

**Comment by pergolafabio** [comment] 2020-07-22 08:28
same here, it works now on refresh, i see the playlist, but i also still see that text in the yellow bar like your second screenshot

**Comment by fondberg** [comment] 2020-07-22 08:29
What is the name of your spotify media player entity?

**Comment by TekniskSupport** [comment] 2020-07-22 08:30
It's
media_player.spotify_player
and defined in the card config like this
```
          spotify_entity: media_player.spotify_player
```

**Comment by fondberg** [comment] 2020-07-22 08:34
Weird, the logic is very simple here. It uses `subscribeEntities(this.hass.connection, (entities) => this.entitiesUpdated(entities));` and then looks for the spotify entity (needed for playback state et.c.)

```
for (const item in entities) {
      // Are there any changes to media players
      if (item.startsWith('media_player')) {
        // Get spotify state
        if (item.startsWith('media_player.spotify_') || item == this.config.spotify_entity) {
          this.spotify_installed = true;
          this.spotify_state = entities[item];
        }
        updateDevices = true;
      }
    }
```

I'll provide a debug build so you can see what entitites are returned

**Comment by pergolafabio** [comment] 2020-07-22 08:35
> It's
> media_player.spotify_player
> and defined in the card config like this
> 
> ```
>           spotify_entity: media_player.spotify_player
> ```

in my case its just : media_player.spotify

and i dont have a "spotify_entity" defined in my yaml for this card
is that needed? i dont see it in the example yaml code

**Comment by fondberg** [comment] 2020-07-22 08:36
Try https://github.com/custom-cards/spotify-card/releases/tag/v2.0.0-beta.21 and look in the console for ENTITIES:

**Comment by pergolafabio** [comment] 2020-07-22 08:37
ok, installed 21 , but what do you mean by, console? in log file?

**Comment by TekniskSupport** [comment] 2020-07-22 08:39
It logs entities twice
and i can see the mediaplayer there
![image](https://user-images.githubusercontent.com/13868526/88154690-751e9f80-cc07-11ea-8aad-86b01dfb47ba.png)

then it throws the error 
![image](https://user-images.githubusercontent.com/13868526/88154800-95e6f500-cc07-11ea-99ee-bc8cb1d855c4.png)

I'll try to reload as many times as it needs to not throw error and see if it's logged more times hang on

**Comment by TekniskSupport** [comment] 2020-07-22 08:44
Yes. When it works it logs the entities 4 times at load
![image](https://user-images.githubusercontent.com/13868526/88155176-0aba2f00-cc08-11ea-90f1-a7ad9d57ff68.png)

then it continues and there are more and more entity objects in the console
so after a little while it looks like this
![image](https://user-images.githubusercontent.com/13868526/88155410-579e0580-cc08-11ea-896f-c6fcce2c3e7b.png)

So when it crashes, (when hass is undefined) no more entities is logged

**Comment by TekniskSupport** [comment] 2020-07-22 08:53
I am in no means a frontend developer and ts/js is not my strongest language. So i'm only guessing here;
But perhaps something like this might do the trick?

https://github.com/home-assistant/frontend/blob/9cad2803e043be4f6c02661ae29de0865ddd02f1/src/entrypoints/app.js#L135

**Comment by fondberg** [comment] 2020-07-22 10:15
What happens is that the hass object doesn't have a connection to ha backend for you. 

Why this is the case I don't know. I will ask other HA devs

**Comment by TekniskSupport** [comment] 2020-07-22 10:48
Perfect, i think this may be the place:
https://discord.com/channels/330944238910963714/460846676358332417

**Comment by fondberg** [comment] 2020-07-22 13:13
@TekniskSupport looking at your screenshot it seems there is some other error than hass.connection being undefined.
I can't see what the error is because the screenshot is cropped. Can you send the error after ENTITIES: has been logged?

**Comment by TekniskSupport** [comment] 2020-07-22 13:32
Yeah, That error i get some times in several views and dashboards, I don't think it's related. Doesn't show up in homeassistant.log or seems to have any effect that I've noticed.

"Unchecked runtime.lastError: The message port closed before a response was received."

![image](https://user-images.githubusercontent.com/13868526/88182479-86c86d00-cc30-11ea-9d3b-928a134c9e35.png)

**Comment by fondberg** [comment] 2020-07-22 15:04
I need to have acces to debug I'm afraid.
Seems like several issues. Not just one.
If that is possible you can contact me on discord @fondberg#5023. I will ha e time around 8pm or else.in the morning tomorrow after 9.30. All times in CET

**Comment by fondberg** [comment] 2020-07-22 15:05
> Yeah, That error i get some times in several views and dashboards, I don't think it's related. Doesn't show up in homeassistant.log or seems to have any effect that I've noticed.
> 
> "Unchecked runtime.lastError: The message port closed before a response was received."
> 
> ![image](https://user-images.githubusercontent.com/13868526/88182479-86c86d00-cc30-11ea-9d3b-928a134c9e35.png)

Seems you might have issues with the connection between front end and backend

**Comment by TekniskSupport** [comment] 2020-07-22 15:21
Hi,

I can try, not certain I'm available tonight family and stuff.
Tomorrow iss probably a safer bet

Can you confirm CET not CEST?

**Comment by fondberg** [comment] 2020-07-22 16:07
CET. Stockholm time

**Comment by TekniskSupport** [comment] 2020-07-22 16:43
Stockholm har sommartid så det blir CEST hojtar till vid 20

**Comment by fondberg** [comment] 2020-07-22 17:35
Jag har fåtr förhinder ikväll. Hör av dig imorgon

**Comment by TekniskSupport** [comment] 2020-07-22 17:59
Aye, hörs imorrn!

**Comment by pergolafabio** [comment] 2020-07-23 06:25
can you guys proceed in english? :-)

anyway, some other question, yesterday i was testing this websocket also, it it possible that somehow this card/spotcast disabled my deconz addon-  that also uses websockets? i never experienced this before, but my deconz was stopped

**Comment by TekniskSupport** [comment] 2020-07-23 06:37
Ofc. no progress so far, but we have a debugging date in about an hour, let's hope we get some results

**Comment by TekniskSupport** [comment] 2020-07-23 09:15
We've made some progress after @fondberg got access to my environment that has the issue.
There seems to be a timing problem and it could be solved by adding a small delay. 
The release v2.0.0-beta.23 has the workaround.

A nicer solution is being looked at.

**Comment by pergolafabio** [comment] 2020-07-23 09:26
yes, installed, seems after refreshing, the playlist are still visible
allthough, i still have that yellow bar with text : "spotify integration has to be installed for playlist information"

**Comment by TekniskSupport** [comment] 2020-07-23 09:48
For me i get the yellow bar on top at first, but after about half a second it disappears,
make sure you reload resources and clear cache after updating, so that the old version is not cached.

Also rename your "media_player.spotify" to "media_player.spotify_somethingelse" (the last underscore is important)
 or define spotify_entity in the card configuration. the configuration value is brand new so i don't think it's documented yet.

**Comment by pergolafabio** [comment] 2020-07-23 09:56
ok, created that entity in card, indeed, now it dissapears after a few sec :)

**Comment by Harry-1976** [comment] 2020-07-23 10:42
Nice to see your progress. Unfortunately i’m not that lucky.

What i have done so far:
I have updated to beta.23 and restarted hass.
I have renamed media_player.spotify to media_player.spotify_hvh
I have selected this media_player and selected the default playlist.
I have refreshed lovelace several times.

Despite all this i still have the warning and the playlist won’t load.

**Comment by TekniskSupport** [comment] 2020-07-23 12:02
I had the playlist appear (even thou it was not working) several iterations ago, perhaps perhaps try removing and reinstalling the spotify integration
([hass base url]/config/integrations)

**Comment by Harry-1976** [comment] 2020-07-23 12:33
Thanks for the heads up. 
I have reinstalled the spotify-integration twice but it makes no difference. I’m puzzled.
The warning disappears after a while but the playlist won’t load.

Spotcast is installed and cookies are configured in config.yaml.
Spotify is installed and account credentials are configured in config.yaml.
Anything else i’m missing?

**Comment by TekniskSupport** [comment] 2020-07-23 12:38
Not sure, perhaps @fondberg has Idéas?
Anything in the homeassistant.log or js console (right click somewhere and choose inspect element, then choose console tab)?

**Comment by Harry-1976** [comment] 2020-07-23 13:13
Quite a lot cache comments. Sorry for turned picture.

![CC836B78-E1F3-42AF-AC0B-221A64CD8F4F](https://user-images.githubusercontent.com/62267225/88290367-f30da400-ccf6-11ea-911b-dd73bfb2b5e4.jpeg)

**Comment by fondberg** [comment] 2020-07-23 16:58
When released most console logs will be removed

**Comment by Harry-1976** [comment] 2020-07-24 12:43
Just updated, restarted HA, cleared cache but playlists still won’t load.

In older beta versions i was able to load featured playlist and discover weekly playlist, but in latest beta versions and in the release version it won’t load any playlist.

Console log is empty. HA-logs are empty as well.

**Comment by fondberg** [comment] 2020-07-24 17:39
Do features playlists or discover weekly work?

**Comment by Harry-1976** [comment] 2020-07-24 18:31
Yes they do.

**Comment by fondberg** [comment] 2020-07-25 07:52
In that case there is nothing wrong with spotcast. The problem must be in spotify. 

You can try to recreate new credentials for spotcast amd of that doesnt work there is nothing that i can do to help

**Comment by Harry-1976** [comment] 2020-07-25 07:58
Thanks. 
I already tried with new cookies but that didnt help.
Anyway thx for the help. Unfortunately i have to switch back to V1.

**Comment by TekniskSupport** [comment] 2020-07-25 15:12
Perhaps this might do it, @Harry-1976 Did you change/add the redirect url  [hass_base_url]/auth/external/callback in the spotify application?
https://developer.spotify.com/dashboard/

**Comment by Harry-1976** [comment] 2020-07-26 08:25
@TekniskSupport No, i haven’t changed that. I don’t get why i does load Featured playlist and Discover Weekly but not my Default playlist.
For now i have switched back to V1.27. That version loads my playlists instantly.

**Comment by TekniskSupport** [comment] 2020-07-26 10:10
If you don't have auth/external/callback as a return uri the spotify integration it's not fully installed. 
Check the documentation for the spotify integration
https://www.home-assistant.io/integrations/spotify/

Perhaps it's using spotcast to retrive the featured and discover weekly as fondberg said?
``` 
In that case there is nothing wrong with spotcast. The problem must be in spotify.
```

**Comment by Harry-1976** [comment] 2020-07-26 11:22
I do have auth/external/callback installed in the Spotify Dashboard. It was already required for V1 of the spotify card.

**Comment by TekniskSupport** [comment] 2020-07-26 11:24
Oh ok, then it wasn't that :( just a thougt..

**Comment by Harry-1976** [comment] 2020-07-26 11:30
I don’t think it is. 
I do remember it took me a while to get it working when i installed V1 of Spotify card. I got ‘ invalid redirect errors’  in the beginning and at some point it suddenly worked (and it still works without problems). 

Thanks for thinking with me. I appreciate it.

**Comment by fondberg** [comment] 2020-07-26 16:28
V2 uses spotcast which used the more powerful browser login. You can test if you csn see any playlists if you login with the same user on https://open.spotify.com

**Comment by dzarlax** [comment] 2020-07-27 16:44
Hi! I've installed v2 (its my first installation) and got this https://l.dzarlax.dev/yZAuO
I've already filled callback, spodcast and Spotify works correctly. Checked with service and Spotify media player. What can be wrong?

**Comment by dzarlax** [comment] 2020-07-27 16:56
> Hi! I've installed v2 (its my first installation) and got this https://l.dzarlax.dev/yZAuO
> I've already filled callback, spodcast and Spotify works correctly. Checked with service and Spotify media player. What can be wrong?

Sorry for the link, fixed.

**Comment by Harry-1976** [comment] 2020-07-27 17:00
> V2 uses spotcast which used the more powerful browser login. You can test if you csn see any playlists if you login with the same user on https://open.spotify.com

Yes, i see all playlists but somehow they will not load.

**Comment by Harry-1976** [comment] 2020-07-27 17:01
> > Hi! I've installed v2 (its my first installation) and got this https://l.dzarlax.dev/yZAuO
> > I've already filled callback, spodcast and Spotify works correctly. Checked with service and Spotify media player. What can be wrong?
> 
> Sorry for the link, fixed.

Hi, How did you fix it?

**Comment by dzarlax** [comment] 2020-07-27 17:02
> > > Hi! I've installed v2 (its my first installation) and got this https://l.dzarlax.dev/yZAuO
> > > I've already filled callback, spodcast and Spotify works correctly. Checked with service and Spotify media player. What can be wrong?
> > 
> > 
> > Sorry for the link, fixed.
> 
> Hi, How did you fix it?

I mean fixed link, it had ssl error =)
The problem is still here, but now it sees that Spotify is installed. https://l.dzarlax.dev/e5Qlj

**Comment by heikkih** [comment] 2020-07-29 14:04
After some debugging with both manual spotipy-calls, javascript in the browser and with playlist-management on my Spotify-account I managed to find a quickfix for this issue on my side. It is not guaranteed that it will fix this issue for everbody but here are some things to try for now:

1. Select the 'default' playlist-type, which is the user playlists
2. Limit the amount of playlists shown to 1.
3. Check the top playlist on your spotify-account, try reordering the playlists and maybe change the names or descriptions.


What I experienced on my side-
- 'featured' and 'discovered-weekly' were working fine. 'default' was not and produced the "spotify integration has to be installed for playback information"-message.
- manual calls with python for requests client.current_users_playlists(limit=1) and client.featured_playlists(limit=1).get("playlists") produced similar and correct json, but I noticed some pipes in the name my own #1 playlist.
- Putting a "clean" playlist on the top fixed the issue.

Cause:
- Escaping issues on the playlist json-strings in either spotify-card or the Hass websocket-library. 
- Spotify's own playlists (featured and discovered weekly) are probably vetted for strange characters like 'pipe', so this only occurs for users who have playlists with problematic chars in name and/or description.

**Comment by heikkih** [comment] 2020-07-29 14:14
btw: this is easily reproducible by saving the following playlist to your library and having it on the top: https://open.spotify.com/playlist/77fqr25dO0BEAmXYLjHjP1 on

**Comment by dzarlax** [comment] 2020-07-29 14:22
> Seems like there are issues with some playlists.
> 
> Try to re-order the playlists and maybe limit the amount of playlists shown to 1.
> 
> My inital thought was that there was some issues with special characters in playlist names, but I couldn't reproduce it on my own playlists.
> 
> I can now easily reproducible this issue by saving the following playlist to my library and having it on the top: https://open.spotify.com/playlist/77fqr25dO0BEAmXYLjHjP1
> 
> Hope that helps in further debugging ;)

Tried this, but didn't help.
https://l.dzarlax.dev/GlQwT

**Comment by heikkih** [comment] 2020-07-29 14:24
> Tried this, but didn't help.
> https://l.dzarlax.dev/GlQwT

Have you tried putting a different playlist on the top of your spotify-library?

**Comment by dzarlax** [comment] 2020-07-29 14:25
> > Tried this, but didn't help.
> > https://l.dzarlax.dev/GlQwT
> 
> Have you tried putting a different playlist on the top of your spotify-library?

Yep, tried several of them with different characters.

**Comment by heikkih** [comment] 2020-07-29 14:25
> > Have you tried putting a different playlist on the top of your spotify-library? 
> Yep, tried several of them with different characters.

Have you tried having a public playlist on top?

**Comment by dzarlax** [comment] 2020-07-29 14:26
> > > Have you tried putting a different playlist on the top of your spotify-library?
> > > Yep, tried several of them with different characters.
> 
> Have you tried having a public playlist on top?

Yes

**Comment by heikkih** [comment] 2020-07-29 14:27
> > > > Have you tried putting a different playlist on the top of your spotify-library?
> > > > Yep, tried several of them with different characters.
> > 
> > 
> > Have you tried having a public playlist on top?
> 
> Yes

Do the 'featured' and 'discovered-weekly' playlist-types work for you?

**Comment by dzarlax** [comment] 2020-07-29 14:45
It started working after I set 1 playlist in text editor. Web control doesn't save settings =(

**Comment by heikkih** [comment] 2020-07-29 14:53
> It started working after I set 1 playlist in text editor. Web control doesn't save settings =(

If I understand it correctly it is now working for you with 1 playlist?

I have a hunch on what the remaining bug is now.
Can you check if any of your top playlists are either empty or is missing a cover image?

**Comment by dzarlax** [comment] 2020-07-29 14:55
Yes, now it's working with freshly replaced playlist!
https://l.dzarlax.dev/B2dq7
https://l.dzarlax.dev/5wuFu

**Comment by heikkih** [comment] 2020-07-29 15:58
Found that the issue I, and probably several else, was seeing was related to playlists which are either empty or not available so they don't have any images. Added a tiny patch for just skipping such playlists for both the listView and the gridView. Pull request created.

**Comment by Harry-1976** [comment] 2020-07-29 16:14
@heikkih You are my hero as that is exactly what is happening.
I started succesfully with 1 playlist, then i did 10 but than my playlists would not load. I can load 6 playlists. Turns out playlist no 7 has no image so no playlist will load.

**Comment by heikkih** [comment] 2020-07-29 22:40
At least now we got this to work, but the patch is just a quickfix. Should probably have a better fix on either including the playlists without images somehow or at least not count them in the amount of playlists shown.

I guess playlists with local files are affected by this as well, and I'm not sure how those can be handled by spotcast.

**Comment by fondberg** [comment] 2020-07-31 08:07
I released the quick fix. In v1 I added a placeholder image. This should be done in v2 also

**Closed** 2020-07-31 09:28 UTC
